# GitHub Pages Configuration
title: Laboratorio de Telemetría y Observabilidad
description: Taller práctico de métricas, logs y dashboards con Prometheus, Grafana y Loki
theme: jekyll-theme-cayman

# GitHub metadata
repository: AndresMarcelo7/no-idp-monitoring-lab

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  parse_block_html: true

# Navigation
show_downloads: false

# Social links
github:
  is_project_page: true

# Exclude files from processing
exclude:
  - CHANGELOG.md
  - assets/css/style.scss
